---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${NAME}${SUFFIX}
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        env: ${TAG_NAME}
    spec:
      description: Allow server ports to be accessed by caddy proxy.
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  role: ${WEB_ROLE}
                  app: ${APP_NAME}${SUFFIX}
                  env: ${TAG_NAME}
              namespaceSelector:
                matchLabels:
                  name: ${NAMESPACE_NAME}
                  environment: ${TAG_NAME}
          ports:
            - protocol: TCP
              port: ${{SERVER_PORT}}
      podSelector:
        matchLabels:
          role: ${ROLE}
          app: ${APP_NAME}${SUFFIX}
          env: ${TAG_NAME}
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        app: ${APP_NAME}${SUFFIX}
        name: ${NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      ports:
        - name: ${NAME}${SUFFIX}
          port: ${{SERVER_PORT}}
          protocol: TCP
          targetPort: ${{SERVER_PORT}}
      selector:
        name: ${NAME}${SUFFIX}
  
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        app: ${APP_NAME}${SUFFIX}
        name: ${NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    stringData:
      tenantId: ${TENANT_ID}
      apiKey: ${API_KEY}
      tractionUrl: ${TRACTION_URL}
      tractionDid: ${TRACTION_DID}
    type: Opaque

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        app: ${APP_NAME}${SUFFIX}
        name: ${NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      replicas: 1
      selector:
        name: ${NAME}${SUFFIX}
      strategy:
        type: Rolling
      template:
        metadata:
          name: ${NAME}${SUFFIX}
          labels:
            app: ${APP_NAME}${SUFFIX}
            name: ${NAME}${SUFFIX}
            app-group: ${APP_GROUP}
            role: ${ROLE}
            env: ${TAG_NAME}
        spec:
          containers:
            - name: ${NAME}${SUFFIX}
              env:
                - name: TENANT_ID
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: tenantId
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: apiKey
                - name: TRACTION_URL
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: tractionUrl
                - name: TRACTION_DID
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: tractionDid
                - name: WEBHOOK_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: webhookSecret
                - name: BASE_ROUTE
                  value: ${BASE_ROUTE}
                - name: STUDENT_VERSION
                  value: ${STUDENT_VERSION}
                - name: LAWYER_VERSION
                  value: ${LAWYER_VERSION}
                - name: PERSON_VERSION
                  value: ${PERSON_VERSION}
              image: " "
              ports:
                - containerPort: ${{SERVER_PORT}}
                  protocol: TCP
              readinessProbe:
                timeoutSeconds: 30
                initialDelaySeconds: 3
                httpGet:
                  path: "/"
                  port: ${{SERVER_PORT}}
              livenessProbe:
                timeoutSeconds: 30
                initialDelaySeconds: 300
                httpGet:
                  path: "/"
                  port: ${{SERVER_PORT}}
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}${SUFFIX}
            from:
              kind: ImageStreamTag
              name: ${NAME}:${TAG_NAME}
              namespace: ${IMAGE_NAMESPACE}

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all the objects defined in this template.
    required: true
    value: bc-wallet-demo-server
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the deployments in this project.
    required: true
    value: bc-wallet-demo
  - name: NAMESPACE_NAME
    displayName: NameSpace name
    description: name of the project namespace
    required: true
    value: a99fd4
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: bc-wallet-demo
  - name: SUFFIX
    displayName: Suffix
    description: A name suffix used for all objects
    required: false
    value: ''
  - name: ROLE
    displayName: Role
    description: The role of this service within the application - used for Network Policies
    required: true
    value: server
  - name: WEB_ROLE
    displayName: proxy role
    description: The role of the caddy proxy service
    required: true
    value: web
  - name: IMAGE_NAMESPACE
    displayName: Namespace containing application images.
    required: true
    value: a99fd4-tools
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod.
    required: true
    value: dev
  - name: SERVER_PORT
    displayName: Server Port
    description: The port on which the service will listen.
    required: true
    value: "5000"
  - name: BASE_ROUTE
    displayName: Base Route
    description: The base route for the backend
    required: false
    value: /digital-trust/showcase
  - name: TENANT_ID
    displayName: Tenant ID
    description: The tenant ID for the traction agent
    required: true
    value: ""
  - name: API_KEY
    displayName: API Key
    description: The API key for the traction agent
    required: true
    value: ""
  - name: WEBHOOK_SECRET
    displayName: Webhook Secret
    description: The secret for the webhook
    required: true
    value: ""
  - name: TRACTION_URL
    displayName: Site URL
    description: The URL for the site
    required: true
    value: ""
  - name: TRACTION_DID
    displayName: Traction DID
    description: The DID for the traction service
    required: true
    value: ""
  - name: STUDENT_VERSION
    displayName: Student Card Version
    description: Schema version for student card
    required: true
    value: "1.0"
  - name: LAWYER_VERSION
    displayName: Member Card Version
    description: Schema version for lsbc member card
    required: true
    value: "1.0"
  - name: PERSON_VERSION
    displayName: Person Credential Version
    description: Schema version for person credential
    required: true
    value: "1.0"
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 10m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 250m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 10Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 1Gi
